/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChooseArea: typeof import('./src/components/ChooseArea/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/Dialog.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Tabs: typeof import('./src/components/Tabs/Tabs.vue')['default']
  }
}
